name: Publish Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Doxygen/**'
      - '.github/workflows/gh-pages.yaml'
      - '.github/doxygen.json'
      - '.github/linkchecker.json'
  pull_request:
    branches:
      - main
    paths:
      - 'Doxygen/**'
      - '.github/workflows/gh-pages.yaml'
      - '.github/doxygen.json'
      - '.github/linkchecker.json'
jobs:
  docs:
    name: Build main documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libclang1-9 libclang-cpp1-9 python
          sudo pip install LinkChecker

      - name: Install doxygen 1.9.2
        run: |
          wget https://doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz
          sudo tar -C /opt -xf doxygen-1.9.2.linux.bin.tar.gz
          sudo ln -s /opt/doxygen-1.9.2/bin/doxygen /usr/local/bin/
          which doxygen
          doxygen --version

      - name: Generate doxygen
        run: |
          echo "::add-matcher::.github/doxygen.json"
          ./gen_doc.sh
          echo "::remove-matcher owner=doxygen::"
        working-directory: ./Doxygen

      - name: Run linkchecker
        run: |
          echo "::add-matcher::.github/linkchecker.json"
          ../Script/check_links.sh ./html/index.html ./
          echo "::remove-matcher owner=linkchecker::"
        working-directory: ./Documentation

      - name: Archive documentation
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: Documentation/html/
          retention-days: 1
          if-no-files-found: error

      - name: Archive documentation
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          cd Documentation/html
          tar -cvjf /tmp/doc.tbz2 .

      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          ref: gh-pages

      - name: Publish documentation
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          rm -r main
          mkdir main
          cd main
          tar -xvjf /tmp/doc.tbz2
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update main documentation"
          git push
